export enum ViewId {
  DEFAULT = 'DEFAULT',
  SECOND = 'SECOND',
  THIRD = 'THIRD',
  
  MAIN_THREE = 'MAIN_THREE',

  THREE_DEMO = 'THREE_DEFAULT',
  THREE_SECOND = 'THREE_SECOND',
  DEMO = 'DEMO',
  DIALOG_MODAL = 'DIALOG_MODAL',
  MAP = 'MAP',
  HOUSE_DISPLAY = 'HOUSE_DISPLAY',
  HOUSE_DIALOG = 'HOUSE_DIALOG',
  FORGERON_GAME = 'FORGERON_GAME',
  SCIENTIFIQUE_GAME = 'SCIENTIFIQUE_GAME',
  STRATEGE_GAME = 'STRATEGE_GAME',
  JARDINIER_GAME = 'JARDINIER_GAME',
  MECANO_GAME = 'MECANO_GAME',
  ROBOT_A_I = 'ROBOT_A_I',
}